//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Scripts/MyInput_Manager.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MyInput_Manager : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MyInput_Manager()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyInput_Manager"",
    ""maps"": [
        {
            ""name"": ""GameplayInput"",
            ""id"": ""7a62538b-cbe4-48fe-9808-6a15de67886b"",
            ""actions"": [
                {
                    ""name"": ""MoveUp"",
                    ""type"": ""Button"",
                    ""id"": ""8e9d9176-638e-41b2-ad3c-8d9fc2552cb0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveDown"",
                    ""type"": ""Button"",
                    ""id"": ""84573ac2-9eda-492c-ba2e-e92e594c2dfd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""d61d6f95-b51f-4ee1-8ede-7e1d92f35103"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""a8cceff0-56f5-4701-9089-1eb1d730d83e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""daa73801-cfc4-4eea-bee2-5ca089a56a18"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""75231e25-b0f5-4634-9719-49ce4f696c3c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""c06dcf24-4b8c-4aa6-9465-134beb039329"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""f5e94442-8f19-4b08-b877-d2297ea40b68"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Return"",
                    ""type"": ""Button"",
                    ""id"": ""57b92857-4aef-47be-be72-fb20ae8ac438"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowUp"",
                    ""type"": ""Button"",
                    ""id"": ""0b9f9483-f175-4074-8c3b-1d4dcbf55abc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowDown"",
                    ""type"": ""Button"",
                    ""id"": ""8449a80b-4643-4a6d-ae07-2b9550db2757"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowLeft"",
                    ""type"": ""Button"",
                    ""id"": ""f17870bf-faa3-4951-919f-f08c7d97ae17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowRight"",
                    ""type"": ""Button"",
                    ""id"": ""2bad419c-c9a8-4091-b49b-f954a9974285"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""32f040d4-05ad-43e0-926d-4fc0fb6f3aa3"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a094e09-f1bb-4071-8451-115f8d06415e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81e7100f-51f0-4f5d-9b23-6cccb1fea363"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af060bd7-9a79-4dec-9b93-01a0b4d4060e"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32562630-560d-4fe7-a2ab-ca1fca524aa0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""426b2b3a-aba1-43de-8ef4-aefc101b8f4f"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48bb3f81-1a97-4f59-b036-97e459fe0cbb"",
                    ""path"": ""<AndroidGamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc7f0cde-e485-4d51-9ce7-c70f0d05ec6f"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3891fb1-064e-43a1-8867-2f252d1cb00f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""527de3b7-bb11-495e-9117-383ab10bd98f"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2af799e7-adf1-4d1e-bf52-2bc3c9507e23"",
                    ""path"": ""<AndroidGamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2b60647-0320-4afb-b000-d38ae1783820"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9c5076d-64aa-4cc3-9bc9-b950fdc526c9"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87bd7e0d-270c-44e3-9269-37f0fe87d333"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30048307-ee4b-4e62-b530-b3cec23516bb"",
                    ""path"": ""<AndroidGamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efcf1be1-0fc1-4ad0-bd06-adb09a6671cb"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2616da6b-f24a-4d0d-b762-292d7698a2f9"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43e05953-fdfb-4069-9080-0f8de5a8218a"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38511f9a-ac06-46c1-a12b-be4f1db1bc45"",
                    ""path"": ""<AndroidGamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c9174bd-ef76-455d-ac83-1b4df7ec5080"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c968d812-6b10-4d0e-a634-845861f1caaa"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f63ae9a0-2be6-436b-bca6-0bfcc421d04e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f11d061b-e095-4730-b2bb-18ae32c1540a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b91a8f41-e4d4-4e1a-8220-c09787370dd4"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2ad6d1b-33e3-401b-9297-9a941eed69a2"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48eec781-dab0-423d-a789-9f4d16bd6001"",
                    ""path"": ""<AndroidGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""063ea72c-7b96-4ed8-9817-94ccab0a2b38"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25468d22-6071-4b81-8b3a-cf530833e015"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dabd48a-874a-4a1f-a618-dedb6c8c01c8"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""674bb5a9-53a2-4e69-b9ad-2a8bc6e55904"",
                    ""path"": ""<AndroidGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6539667-9273-4520-8dd6-6446a315c8ca"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d512915-0652-4027-b418-4b4e84ab3a07"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb438b72-571b-47d6-a931-e3771c1724b3"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac97e3eb-d096-44f5-a092-ad9d158916e0"",
                    ""path"": ""<AndroidGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Return"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf58a0ba-e186-4777-a6fa-94402ad640b3"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91786db7-8fb6-4f74-86d3-b00933474244"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bd6f82a-a8b4-428b-af09-d2761e3fbbf2"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d9595e1-da0c-495c-a769-5ca79cef2eab"",
                    ""path"": ""<AndroidGamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8761fa6f-55be-4eb4-8275-0ec39b03262c"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e0eaf1a-3b4c-4798-a819-531f4d07f479"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98da2077-82ae-453f-a21a-e8a9b7cbe0a8"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""829dd3b8-0923-4451-9534-2f94c34fc3ac"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17727656-f897-4619-ad1b-49d00eeec7b8"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5691fb45-7e89-4358-836a-5fae33894ac3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""970a3c60-02fc-406a-9728-790b8980dbc4"",
                    ""path"": ""<AndroidGamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccb2ea61-53ed-44e5-8f45-05e6f49efde5"",
                    ""path"": ""<AndroidGamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""GamePad"",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""AndroidInput"",
            ""id"": ""0f75e656-003f-480f-8759-c012da98cf03"",
            ""actions"": [
                {
                    ""name"": ""D_PAD UP"",
                    ""type"": ""Button"",
                    ""id"": ""33df1d84-c033-402d-93e0-84013f42e9d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""D_PAD DOWN"",
                    ""type"": ""Button"",
                    ""id"": ""f574d120-cc32-4ea3-8a68-c97a876e87ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""D_PAD LEFT"",
                    ""type"": ""Button"",
                    ""id"": ""3cd56387-9dee-4267-a0e0-9a5ea20a1171"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""D_PAD RIGHT"",
                    ""type"": ""Button"",
                    ""id"": ""a7d3f74f-73a3-421e-bf20-6721eeeee6f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SPACE_A"",
                    ""type"": ""Button"",
                    ""id"": ""3d408b41-b187-4784-9823-e292d0cb16dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""START_ENTER"",
                    ""type"": ""Button"",
                    ""id"": ""1e0b6747-5489-4a9b-8628-3e631304cbb9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""W_MOVE_UP"",
                    ""type"": ""Button"",
                    ""id"": ""2caf5673-52d8-4b24-b665-ffb1e8f63d67"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""A_MOVE_LEFT"",
                    ""type"": ""Button"",
                    ""id"": ""be27bb16-b15a-4003-896f-a20e0a7d4e89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""S_MOVE_DOWN"",
                    ""type"": ""Button"",
                    ""id"": ""750603d7-3a2f-41e6-bd06-b3b13fbeb2f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""D_MOVE_RIGHT"",
                    ""type"": ""Button"",
                    ""id"": ""8ec596cc-567a-4e7a-8959-1627506efe08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ESC_B"",
                    ""type"": ""Button"",
                    ""id"": ""74d047a4-b52e-4e8e-aec5-0ced0227614b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SHIFT_R2"",
                    ""type"": ""Button"",
                    ""id"": ""d6c11f29-b1de-47f6-8897-1ccdec809f1d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""E_L2"",
                    ""type"": ""Button"",
                    ""id"": ""1d53b5f1-da14-44a5-bacc-4b1b3f9bacd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0bde7be6-6452-444c-86ed-61ad457ec003"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0202d1a8-5fa5-4086-b685-d6118c76bfe7"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fb6f09d-32f5-456c-a642-f7ca142a1dcc"",
                    ""path"": ""<AndroidGamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46d92cca-3923-4937-808e-8b04e8c296e5"",
                    ""path"": ""<NimbusGamepadHid>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e0d3d8d-0b7b-4266-ad68-3eaf77813bb1"",
                    ""path"": ""<iOSGameController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a7460b9-b0da-4223-83f8-d3b94e18f80a"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/hat/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40c75398-1b91-486f-8aee-127f0426a6de"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d8c0734-900f-45a7-b820-3c1aa21567a8"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfc907dd-c96e-4de8-9f6c-84e894e8d5e0"",
                    ""path"": ""<AndroidGamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""331ca3f0-093b-473d-ade4-7d39c3ef981e"",
                    ""path"": ""<iOSGameController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98767556-1d64-44e3-ae3b-0adf014d2ed4"",
                    ""path"": ""<NimbusGamepadHid>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7bd2181-63ac-49d0-b5bb-0eb864408a52"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/hat/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83f603f5-9509-4c4a-b880-373c15df1f04"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b372d604-0346-4cbb-ae41-491e6d394fc8"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30e933b2-c6da-4845-a8c4-c39262563193"",
                    ""path"": ""<AndroidGamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26904b03-d673-4073-8ff8-cdb1777cab38"",
                    ""path"": ""<iOSGameController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""134819bd-2639-4f64-99c4-87fb31d3d50a"",
                    ""path"": ""<NimbusGamepadHid>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e4de941-cc39-4bca-97d9-9226a3a49bbd"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/hat/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63482e69-1247-454b-8108-c2c66aabaf07"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e2b63d2-f6c8-4e61-b5e8-942960fd5b7c"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfb57f11-d81a-4270-81e5-f4ff33d8526d"",
                    ""path"": ""<AndroidGamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""019f0bfd-db31-4872-b349-53edbcf30e74"",
                    ""path"": ""<iOSGameController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4742bd90-76e0-4210-9679-7aeaa8bcdb0f"",
                    ""path"": ""<NimbusGamepadHid>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc168d90-e0bf-4055-989a-a632c28610d1"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/hat/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_PAD RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2f3a3c7-9ee4-458f-a870-6143bdb89cca"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SPACE_A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b11353f-6924-4fb6-8d1c-4e410d8816cf"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SPACE_A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""316d1059-6771-4035-872b-94f5e6725502"",
                    ""path"": ""<AndroidGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SPACE_A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9399b7be-1d81-43b4-a654-3d213172ffb0"",
                    ""path"": ""<iOSGameController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SPACE_A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f40e7d92-5710-475c-a0dd-c8bd6b7c8388"",
                    ""path"": ""<NimbusGamepadHid>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SPACE_A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""312e56cb-e540-4e3c-9e8f-db90f7fd4532"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SPACE_A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b30912b-8855-46ae-a188-7aa26f0d215d"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""START_ENTER"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1702caed-c938-400b-af15-84785fbab3db"",
                    ""path"": ""<AndroidGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""START_ENTER"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb0d565f-b217-48f6-9382-b9d6734bdd60"",
                    ""path"": ""<iOSGameController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""START_ENTER"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c491a1c-35f5-439d-8f98-afb75debef5c"",
                    ""path"": ""<NimbusGamepadHid>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""START_ENTER"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ff18af5-87d2-4971-86fa-cc753db60b44"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""START_ENTER"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93e095d6-8dc4-444b-ada5-0db17c425e06"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""START_ENTER"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc5b37e4-a459-42ca-902d-57470a9bbead"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""W_MOVE_UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5361ce8-7f2c-4226-ae41-b903a37150e9"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""W_MOVE_UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccd9a1fd-ce78-4303-aaf0-324314d4567e"",
                    ""path"": ""<iOSGameController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""W_MOVE_UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0832d550-a520-4437-9bbd-2a627de1b99d"",
                    ""path"": ""<AndroidGamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""W_MOVE_UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""301d5ae9-ef2b-4397-bb00-132d64edae55"",
                    ""path"": ""<NimbusGamepadHid>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""W_MOVE_UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c53cfc4-2216-446a-9ca9-6f99e27adcb4"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""W_MOVE_UP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3452db9e-22d7-42ee-9e1d-0761fdae0153"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""S_MOVE_DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be4905a8-b74c-41a1-acb0-c6448ec579e7"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""S_MOVE_DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12d026fb-f661-43ca-af46-4c31fd2a754d"",
                    ""path"": ""<iOSGameController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""S_MOVE_DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fe2d97c-ba8d-476f-af14-8e8b56071829"",
                    ""path"": ""<AndroidGamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""S_MOVE_DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ad4f407-870c-4cb7-b824-7482e0e1e342"",
                    ""path"": ""<NimbusGamepadHid>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""S_MOVE_DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84202b94-924a-49a4-8471-1344f4b704ce"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""S_MOVE_DOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32dc6548-7ea7-4590-9baa-062ca61438d1"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_MOVE_RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9b0711a-190f-48a2-93a3-2f1a6b28be7b"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_MOVE_RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9639c34-bfd8-4fe7-aad6-155fb32319b1"",
                    ""path"": ""<iOSGameController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_MOVE_RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f20c2be9-6fe2-466a-9f35-c77a23d7a7a5"",
                    ""path"": ""<AndroidGamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_MOVE_RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06b9e153-eed3-4faa-a790-01e5ec27d7cb"",
                    ""path"": ""<NimbusGamepadHid>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_MOVE_RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbd55287-b4a5-4040-9178-2fa36939aa2d"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D_MOVE_RIGHT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d091813-dffe-4c60-b51d-a54530342691"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ESC_B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca272ac9-755e-4f4b-8d55-761143703903"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ESC_B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f4b1639-1acb-423f-a0a4-0d8d9fd7c2fe"",
                    ""path"": ""<iOSGameController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ESC_B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae8dc3de-c41d-42b2-b1c9-68ce477f1443"",
                    ""path"": ""<AndroidGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ESC_B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f73272a-5474-4ba2-a081-35ebd4c60ec7"",
                    ""path"": ""<NimbusGamepadHid>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ESC_B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d1060e3-5dee-4149-a2fd-bd1b371596a8"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ESC_B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4032e24f-8c67-48d6-a720-f2b0ff2e7726"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_MOVE_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""101032b8-013b-4068-adad-2347348d3b4c"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_MOVE_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f507e5d3-c8bf-49e8-a046-8fa23de17a24"",
                    ""path"": ""<iOSGameController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_MOVE_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a587601e-7303-45b3-b0e2-1030c5c989c2"",
                    ""path"": ""<AndroidGamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_MOVE_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e059618-ce05-42bd-9e3c-7261b4025759"",
                    ""path"": ""<NimbusGamepadHid>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_MOVE_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4873fcb0-b3f5-471b-aba4-d7ef4d07f744"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A_MOVE_LEFT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54979e9d-acb4-4b6e-9d81-486a9982ba1c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SHIFT_R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3044b2a2-302b-4c35-9610-ad8f47d1a0f6"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SHIFT_R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea03bf38-4a74-46ae-bc6d-f46b27e34c5e"",
                    ""path"": ""<iOSGameController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SHIFT_R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97312541-15e4-4f39-86e6-6950a1e4a305"",
                    ""path"": ""<AndroidGamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SHIFT_R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31c56232-131d-486c-a0d2-a06aa42edccd"",
                    ""path"": ""<NimbusGamepadHid>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SHIFT_R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f30be78-7cf6-429c-9677-90def61e5ba0"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/button10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SHIFT_R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6155f797-7942-4ea7-998f-1643d54a3ab5"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E_L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cdecf1c3-0c9a-4b51-b920-f0b6a077e79d"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E_L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6bd951b-c49e-4bd2-8df2-15ce4ca88258"",
                    ""path"": ""<iOSGameController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E_L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73b6c3cd-e7d9-4564-b5ad-bb76949ce1a5"",
                    ""path"": ""<AndroidGamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E_L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd057a99-bd63-400f-bef4-f4255cfb9cd4"",
                    ""path"": ""<NimbusGamepadHid>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E_L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0298039b-e0b3-439b-8db3-229279232e20"",
                    ""path"": ""<HID::MOCUTE  Gamepad >/button9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""E_L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""GamePad"",
            ""bindingGroup"": ""GamePad"",
            ""devices"": [
                {
                    ""devicePath"": ""<AndroidGamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // GameplayInput
        m_GameplayInput = asset.FindActionMap("GameplayInput", throwIfNotFound: true);
        m_GameplayInput_MoveUp = m_GameplayInput.FindAction("MoveUp", throwIfNotFound: true);
        m_GameplayInput_MoveDown = m_GameplayInput.FindAction("MoveDown", throwIfNotFound: true);
        m_GameplayInput_MoveLeft = m_GameplayInput.FindAction("MoveLeft", throwIfNotFound: true);
        m_GameplayInput_MoveRight = m_GameplayInput.FindAction("MoveRight", throwIfNotFound: true);
        m_GameplayInput_Run = m_GameplayInput.FindAction("Run", throwIfNotFound: true);
        m_GameplayInput_Aim = m_GameplayInput.FindAction("Aim", throwIfNotFound: true);
        m_GameplayInput_Select = m_GameplayInput.FindAction("Select", throwIfNotFound: true);
        m_GameplayInput_Esc = m_GameplayInput.FindAction("Esc", throwIfNotFound: true);
        m_GameplayInput_Return = m_GameplayInput.FindAction("Return", throwIfNotFound: true);
        m_GameplayInput_ArrowUp = m_GameplayInput.FindAction("ArrowUp", throwIfNotFound: true);
        m_GameplayInput_ArrowDown = m_GameplayInput.FindAction("ArrowDown", throwIfNotFound: true);
        m_GameplayInput_ArrowLeft = m_GameplayInput.FindAction("ArrowLeft", throwIfNotFound: true);
        m_GameplayInput_ArrowRight = m_GameplayInput.FindAction("ArrowRight", throwIfNotFound: true);
        // AndroidInput
        m_AndroidInput = asset.FindActionMap("AndroidInput", throwIfNotFound: true);
        m_AndroidInput_D_PADUP = m_AndroidInput.FindAction("D_PAD UP", throwIfNotFound: true);
        m_AndroidInput_D_PADDOWN = m_AndroidInput.FindAction("D_PAD DOWN", throwIfNotFound: true);
        m_AndroidInput_D_PADLEFT = m_AndroidInput.FindAction("D_PAD LEFT", throwIfNotFound: true);
        m_AndroidInput_D_PADRIGHT = m_AndroidInput.FindAction("D_PAD RIGHT", throwIfNotFound: true);
        m_AndroidInput_SPACE_A = m_AndroidInput.FindAction("SPACE_A", throwIfNotFound: true);
        m_AndroidInput_START_ENTER = m_AndroidInput.FindAction("START_ENTER", throwIfNotFound: true);
        m_AndroidInput_W_MOVE_UP = m_AndroidInput.FindAction("W_MOVE_UP", throwIfNotFound: true);
        m_AndroidInput_A_MOVE_LEFT = m_AndroidInput.FindAction("A_MOVE_LEFT", throwIfNotFound: true);
        m_AndroidInput_S_MOVE_DOWN = m_AndroidInput.FindAction("S_MOVE_DOWN", throwIfNotFound: true);
        m_AndroidInput_D_MOVE_RIGHT = m_AndroidInput.FindAction("D_MOVE_RIGHT", throwIfNotFound: true);
        m_AndroidInput_ESC_B = m_AndroidInput.FindAction("ESC_B", throwIfNotFound: true);
        m_AndroidInput_SHIFT_R2 = m_AndroidInput.FindAction("SHIFT_R2", throwIfNotFound: true);
        m_AndroidInput_E_L2 = m_AndroidInput.FindAction("E_L2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameplayInput
    private readonly InputActionMap m_GameplayInput;
    private IGameplayInputActions m_GameplayInputActionsCallbackInterface;
    private readonly InputAction m_GameplayInput_MoveUp;
    private readonly InputAction m_GameplayInput_MoveDown;
    private readonly InputAction m_GameplayInput_MoveLeft;
    private readonly InputAction m_GameplayInput_MoveRight;
    private readonly InputAction m_GameplayInput_Run;
    private readonly InputAction m_GameplayInput_Aim;
    private readonly InputAction m_GameplayInput_Select;
    private readonly InputAction m_GameplayInput_Esc;
    private readonly InputAction m_GameplayInput_Return;
    private readonly InputAction m_GameplayInput_ArrowUp;
    private readonly InputAction m_GameplayInput_ArrowDown;
    private readonly InputAction m_GameplayInput_ArrowLeft;
    private readonly InputAction m_GameplayInput_ArrowRight;
    public struct GameplayInputActions
    {
        private @MyInput_Manager m_Wrapper;
        public GameplayInputActions(@MyInput_Manager wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveUp => m_Wrapper.m_GameplayInput_MoveUp;
        public InputAction @MoveDown => m_Wrapper.m_GameplayInput_MoveDown;
        public InputAction @MoveLeft => m_Wrapper.m_GameplayInput_MoveLeft;
        public InputAction @MoveRight => m_Wrapper.m_GameplayInput_MoveRight;
        public InputAction @Run => m_Wrapper.m_GameplayInput_Run;
        public InputAction @Aim => m_Wrapper.m_GameplayInput_Aim;
        public InputAction @Select => m_Wrapper.m_GameplayInput_Select;
        public InputAction @Esc => m_Wrapper.m_GameplayInput_Esc;
        public InputAction @Return => m_Wrapper.m_GameplayInput_Return;
        public InputAction @ArrowUp => m_Wrapper.m_GameplayInput_ArrowUp;
        public InputAction @ArrowDown => m_Wrapper.m_GameplayInput_ArrowDown;
        public InputAction @ArrowLeft => m_Wrapper.m_GameplayInput_ArrowLeft;
        public InputAction @ArrowRight => m_Wrapper.m_GameplayInput_ArrowRight;
        public InputActionMap Get() { return m_Wrapper.m_GameplayInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayInputActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayInputActions instance)
        {
            if (m_Wrapper.m_GameplayInputActionsCallbackInterface != null)
            {
                @MoveUp.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveUp;
                @MoveUp.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveUp;
                @MoveUp.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveUp;
                @MoveDown.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveDown;
                @MoveDown.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveDown;
                @MoveDown.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveDown;
                @MoveLeft.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveLeft;
                @MoveRight.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveRight;
                @MoveRight.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveRight;
                @MoveRight.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnMoveRight;
                @Run.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnRun;
                @Aim.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnAim;
                @Select.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnSelect;
                @Esc.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnEsc;
                @Esc.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnEsc;
                @Esc.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnEsc;
                @Return.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnReturn;
                @Return.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnReturn;
                @Return.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnReturn;
                @ArrowUp.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowUp;
                @ArrowUp.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowUp;
                @ArrowUp.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowUp;
                @ArrowDown.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowDown;
                @ArrowDown.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowDown;
                @ArrowDown.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowDown;
                @ArrowLeft.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowLeft;
                @ArrowLeft.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowLeft;
                @ArrowLeft.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowLeft;
                @ArrowRight.started -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowRight;
                @ArrowRight.performed -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowRight;
                @ArrowRight.canceled -= m_Wrapper.m_GameplayInputActionsCallbackInterface.OnArrowRight;
            }
            m_Wrapper.m_GameplayInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveUp.started += instance.OnMoveUp;
                @MoveUp.performed += instance.OnMoveUp;
                @MoveUp.canceled += instance.OnMoveUp;
                @MoveDown.started += instance.OnMoveDown;
                @MoveDown.performed += instance.OnMoveDown;
                @MoveDown.canceled += instance.OnMoveDown;
                @MoveLeft.started += instance.OnMoveLeft;
                @MoveLeft.performed += instance.OnMoveLeft;
                @MoveLeft.canceled += instance.OnMoveLeft;
                @MoveRight.started += instance.OnMoveRight;
                @MoveRight.performed += instance.OnMoveRight;
                @MoveRight.canceled += instance.OnMoveRight;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Esc.started += instance.OnEsc;
                @Esc.performed += instance.OnEsc;
                @Esc.canceled += instance.OnEsc;
                @Return.started += instance.OnReturn;
                @Return.performed += instance.OnReturn;
                @Return.canceled += instance.OnReturn;
                @ArrowUp.started += instance.OnArrowUp;
                @ArrowUp.performed += instance.OnArrowUp;
                @ArrowUp.canceled += instance.OnArrowUp;
                @ArrowDown.started += instance.OnArrowDown;
                @ArrowDown.performed += instance.OnArrowDown;
                @ArrowDown.canceled += instance.OnArrowDown;
                @ArrowLeft.started += instance.OnArrowLeft;
                @ArrowLeft.performed += instance.OnArrowLeft;
                @ArrowLeft.canceled += instance.OnArrowLeft;
                @ArrowRight.started += instance.OnArrowRight;
                @ArrowRight.performed += instance.OnArrowRight;
                @ArrowRight.canceled += instance.OnArrowRight;
            }
        }
    }
    public GameplayInputActions @GameplayInput => new GameplayInputActions(this);

    // AndroidInput
    private readonly InputActionMap m_AndroidInput;
    private IAndroidInputActions m_AndroidInputActionsCallbackInterface;
    private readonly InputAction m_AndroidInput_D_PADUP;
    private readonly InputAction m_AndroidInput_D_PADDOWN;
    private readonly InputAction m_AndroidInput_D_PADLEFT;
    private readonly InputAction m_AndroidInput_D_PADRIGHT;
    private readonly InputAction m_AndroidInput_SPACE_A;
    private readonly InputAction m_AndroidInput_START_ENTER;
    private readonly InputAction m_AndroidInput_W_MOVE_UP;
    private readonly InputAction m_AndroidInput_A_MOVE_LEFT;
    private readonly InputAction m_AndroidInput_S_MOVE_DOWN;
    private readonly InputAction m_AndroidInput_D_MOVE_RIGHT;
    private readonly InputAction m_AndroidInput_ESC_B;
    private readonly InputAction m_AndroidInput_SHIFT_R2;
    private readonly InputAction m_AndroidInput_E_L2;
    public struct AndroidInputActions
    {
        private @MyInput_Manager m_Wrapper;
        public AndroidInputActions(@MyInput_Manager wrapper) { m_Wrapper = wrapper; }
        public InputAction @D_PADUP => m_Wrapper.m_AndroidInput_D_PADUP;
        public InputAction @D_PADDOWN => m_Wrapper.m_AndroidInput_D_PADDOWN;
        public InputAction @D_PADLEFT => m_Wrapper.m_AndroidInput_D_PADLEFT;
        public InputAction @D_PADRIGHT => m_Wrapper.m_AndroidInput_D_PADRIGHT;
        public InputAction @SPACE_A => m_Wrapper.m_AndroidInput_SPACE_A;
        public InputAction @START_ENTER => m_Wrapper.m_AndroidInput_START_ENTER;
        public InputAction @W_MOVE_UP => m_Wrapper.m_AndroidInput_W_MOVE_UP;
        public InputAction @A_MOVE_LEFT => m_Wrapper.m_AndroidInput_A_MOVE_LEFT;
        public InputAction @S_MOVE_DOWN => m_Wrapper.m_AndroidInput_S_MOVE_DOWN;
        public InputAction @D_MOVE_RIGHT => m_Wrapper.m_AndroidInput_D_MOVE_RIGHT;
        public InputAction @ESC_B => m_Wrapper.m_AndroidInput_ESC_B;
        public InputAction @SHIFT_R2 => m_Wrapper.m_AndroidInput_SHIFT_R2;
        public InputAction @E_L2 => m_Wrapper.m_AndroidInput_E_L2;
        public InputActionMap Get() { return m_Wrapper.m_AndroidInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AndroidInputActions set) { return set.Get(); }
        public void SetCallbacks(IAndroidInputActions instance)
        {
            if (m_Wrapper.m_AndroidInputActionsCallbackInterface != null)
            {
                @D_PADUP.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADUP;
                @D_PADUP.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADUP;
                @D_PADUP.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADUP;
                @D_PADDOWN.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADDOWN;
                @D_PADDOWN.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADDOWN;
                @D_PADDOWN.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADDOWN;
                @D_PADLEFT.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADLEFT;
                @D_PADLEFT.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADLEFT;
                @D_PADLEFT.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADLEFT;
                @D_PADRIGHT.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADRIGHT;
                @D_PADRIGHT.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADRIGHT;
                @D_PADRIGHT.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_PADRIGHT;
                @SPACE_A.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnSPACE_A;
                @SPACE_A.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnSPACE_A;
                @SPACE_A.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnSPACE_A;
                @START_ENTER.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnSTART_ENTER;
                @START_ENTER.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnSTART_ENTER;
                @START_ENTER.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnSTART_ENTER;
                @W_MOVE_UP.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnW_MOVE_UP;
                @W_MOVE_UP.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnW_MOVE_UP;
                @W_MOVE_UP.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnW_MOVE_UP;
                @A_MOVE_LEFT.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnA_MOVE_LEFT;
                @A_MOVE_LEFT.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnA_MOVE_LEFT;
                @A_MOVE_LEFT.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnA_MOVE_LEFT;
                @S_MOVE_DOWN.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnS_MOVE_DOWN;
                @S_MOVE_DOWN.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnS_MOVE_DOWN;
                @S_MOVE_DOWN.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnS_MOVE_DOWN;
                @D_MOVE_RIGHT.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_MOVE_RIGHT;
                @D_MOVE_RIGHT.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_MOVE_RIGHT;
                @D_MOVE_RIGHT.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnD_MOVE_RIGHT;
                @ESC_B.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnESC_B;
                @ESC_B.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnESC_B;
                @ESC_B.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnESC_B;
                @SHIFT_R2.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnSHIFT_R2;
                @SHIFT_R2.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnSHIFT_R2;
                @SHIFT_R2.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnSHIFT_R2;
                @E_L2.started -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnE_L2;
                @E_L2.performed -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnE_L2;
                @E_L2.canceled -= m_Wrapper.m_AndroidInputActionsCallbackInterface.OnE_L2;
            }
            m_Wrapper.m_AndroidInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @D_PADUP.started += instance.OnD_PADUP;
                @D_PADUP.performed += instance.OnD_PADUP;
                @D_PADUP.canceled += instance.OnD_PADUP;
                @D_PADDOWN.started += instance.OnD_PADDOWN;
                @D_PADDOWN.performed += instance.OnD_PADDOWN;
                @D_PADDOWN.canceled += instance.OnD_PADDOWN;
                @D_PADLEFT.started += instance.OnD_PADLEFT;
                @D_PADLEFT.performed += instance.OnD_PADLEFT;
                @D_PADLEFT.canceled += instance.OnD_PADLEFT;
                @D_PADRIGHT.started += instance.OnD_PADRIGHT;
                @D_PADRIGHT.performed += instance.OnD_PADRIGHT;
                @D_PADRIGHT.canceled += instance.OnD_PADRIGHT;
                @SPACE_A.started += instance.OnSPACE_A;
                @SPACE_A.performed += instance.OnSPACE_A;
                @SPACE_A.canceled += instance.OnSPACE_A;
                @START_ENTER.started += instance.OnSTART_ENTER;
                @START_ENTER.performed += instance.OnSTART_ENTER;
                @START_ENTER.canceled += instance.OnSTART_ENTER;
                @W_MOVE_UP.started += instance.OnW_MOVE_UP;
                @W_MOVE_UP.performed += instance.OnW_MOVE_UP;
                @W_MOVE_UP.canceled += instance.OnW_MOVE_UP;
                @A_MOVE_LEFT.started += instance.OnA_MOVE_LEFT;
                @A_MOVE_LEFT.performed += instance.OnA_MOVE_LEFT;
                @A_MOVE_LEFT.canceled += instance.OnA_MOVE_LEFT;
                @S_MOVE_DOWN.started += instance.OnS_MOVE_DOWN;
                @S_MOVE_DOWN.performed += instance.OnS_MOVE_DOWN;
                @S_MOVE_DOWN.canceled += instance.OnS_MOVE_DOWN;
                @D_MOVE_RIGHT.started += instance.OnD_MOVE_RIGHT;
                @D_MOVE_RIGHT.performed += instance.OnD_MOVE_RIGHT;
                @D_MOVE_RIGHT.canceled += instance.OnD_MOVE_RIGHT;
                @ESC_B.started += instance.OnESC_B;
                @ESC_B.performed += instance.OnESC_B;
                @ESC_B.canceled += instance.OnESC_B;
                @SHIFT_R2.started += instance.OnSHIFT_R2;
                @SHIFT_R2.performed += instance.OnSHIFT_R2;
                @SHIFT_R2.canceled += instance.OnSHIFT_R2;
                @E_L2.started += instance.OnE_L2;
                @E_L2.performed += instance.OnE_L2;
                @E_L2.canceled += instance.OnE_L2;
            }
        }
    }
    public AndroidInputActions @AndroidInput => new AndroidInputActions(this);
    private int m_GamePadSchemeIndex = -1;
    public InputControlScheme GamePadScheme
    {
        get
        {
            if (m_GamePadSchemeIndex == -1) m_GamePadSchemeIndex = asset.FindControlSchemeIndex("GamePad");
            return asset.controlSchemes[m_GamePadSchemeIndex];
        }
    }
    public interface IGameplayInputActions
    {
        void OnMoveUp(InputAction.CallbackContext context);
        void OnMoveDown(InputAction.CallbackContext context);
        void OnMoveLeft(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnEsc(InputAction.CallbackContext context);
        void OnReturn(InputAction.CallbackContext context);
        void OnArrowUp(InputAction.CallbackContext context);
        void OnArrowDown(InputAction.CallbackContext context);
        void OnArrowLeft(InputAction.CallbackContext context);
        void OnArrowRight(InputAction.CallbackContext context);
    }
    public interface IAndroidInputActions
    {
        void OnD_PADUP(InputAction.CallbackContext context);
        void OnD_PADDOWN(InputAction.CallbackContext context);
        void OnD_PADLEFT(InputAction.CallbackContext context);
        void OnD_PADRIGHT(InputAction.CallbackContext context);
        void OnSPACE_A(InputAction.CallbackContext context);
        void OnSTART_ENTER(InputAction.CallbackContext context);
        void OnW_MOVE_UP(InputAction.CallbackContext context);
        void OnA_MOVE_LEFT(InputAction.CallbackContext context);
        void OnS_MOVE_DOWN(InputAction.CallbackContext context);
        void OnD_MOVE_RIGHT(InputAction.CallbackContext context);
        void OnESC_B(InputAction.CallbackContext context);
        void OnSHIFT_R2(InputAction.CallbackContext context);
        void OnE_L2(InputAction.CallbackContext context);
    }
}
